<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "go_easyslider"
 *
 * Auto generated by Extension Builder 2015-05-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'JZ Cart',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Jawad Zaib',
	'author_email' => 'jawadzaib3@gmail.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'go_backend' => '0.3.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);